# 本项目是public，需要独立配置Action Secret：GPR_USR、GPR_KEY
name: release-please
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  issues: write # This is important for label creation
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GPR_USR: ${{ secrets.GPR_USR }}
      GPR_KEY: ${{ secrets.GPR_KEY }}
      ROOM_ID: "oc_44bf0d50f218c0e0074ed8644e620cef"

    steps:
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v4.7.1
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
        if: ${{ steps.release.outputs.release_created }}

      - name: Check Java version
        run: java -version
        if: ${{ steps.release.outputs.release_created }}

      # https://github.com/googleapis/release-please-action
      - uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          release-type: simple

      # https://github.com/actions/checkout
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.release_created }}

      - name: Cache gradle
        # https://github.com/actions/cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        if: ${{ steps.release.outputs.release_created }}

      - run: echo ${{ steps.release.outputs.tag_name }} > lib_version.txt
        if: ${{ steps.release.outputs.release_created }}

      - run: ./gradlew publish
        if: ${{ steps.release.outputs.release_created }}

      - name: Send pr notification
        run: |
          curl -XPOST \
          -H "Content-Type:application/json" \
          -H "X-SPACESHIP-TOKEN:${{ secrets.SPACESHIP_TOKEN }}" \
          https://spaceship.etm.tech/hubot/notify \
          -d '{"roomId":"${{ env.ROOM_ID }}","action":"${{ env.GITHUB_REPOSITORY }}","msg":"${{ github.repository }}有新 Pull request，[点击查看](https://github.com/${{ github.repository }}/pulls)"}'
        if: ${{ steps.release.outputs.release_created == false}}

      - name: Send release notification
        run: |
          curl -XPOST \
          -H "Content-Type:application/json" \
          -H "X-SPACESHIP-TOKEN:${{ secrets.SPACESHIP_TOKEN }}" \
          https://spaceship.etm.tech/hubot/notify \
          -d '{"roomId":"${{ env.ROOM_ID }}","action":"${{ env.GITHUB_REPOSITORY }}","msg":"${{ github.repository }}发布了新版本，[点击查看](https://github.com/${{ github.repository }}/releases)"}'
        if: ${{ steps.release.outputs.release_created }}